name = "spend-analysis-demo"
compatibility_date = "2024-10-06"

[env.production]
account_id = "40f316de02cef7268076b14d80b373ba"

[[env.production.route]]
pattern = "spend.solutoconsulting.com/*"
zone_name = "solutoconsulting.com"